baseURL = "https://achikuan.github.io/"
languageCode = "zh-tw"
title = "kyw的隨筆"
theme = "bodhi"
# googleAnalytics = "UA-123-45"
DisqusShortname = "achikuan"

[params]
    subtitle = "一個廢物的資訊筆記"
    avatar = "/image/kyw.png"
    author = "AchiKuan"
    commentoSrc = "https://commento.example.com/js/commento.js"
    footerMessage = "我不知道路有多長，但是我知道我走了多少 Email: sereter19@gmail.com"
    disableSearch = false

[[menu.main]]
name = "首頁"
url = "/"
weight = 1

[[menu.main_right]]
name = "關於"
url = "/about/"
weight = 1

[[menu.nav]]
name = "文章"
url = "/posts"
weight = 1

[[menu.nav]]
parent = "文章"
name = "標籤"
url = "/tags"
weight = 2

[[menu.nav]]
parent = "文章"
name = "分類"
url = "/categories"
weight = 3

[[menu.nav]]
parent = "文章"
name = "歷史"
url = "/archive"
weight = 3

[markup.goldmark.renderer]
unsafe= true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    noClasses = false
    tabWidth = 4

[[params.social]]
name = "Contact me"
icon = "send"
url = "https://linktr.ee/KuanYuWei"
